apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-amqp-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ed254-consumer-validator.labels" . | nindent 4 }}
type: Opaque
stringData:
  AMQP_BROKER_USERNAME: {{ .Values.amqp.username | quote }}
  AMQP_BROKER_PASSWORD: {{ .Values.amqp.password | quote }}
