apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ed254-consumer-validator-client-certificate
  namespace: swim-demo
spec:
  secretName: ed254-consumer-validator-client-tls
  issuerRef:
    name: swim-ca-issuer
    kind: ClusterIssuer
  commonName: ed254-consumer-validator-client
  usages:
    - digital signature
    - key encipherment
    - client auth
  privateKey:
    algorithm: RSA
    size: 2048
