apiVersion: v1
kind: Secret
metadata:
  name: ed254-consumer-validator-amqp-credentials
  namespace: swim-demo
  labels:
    app: ed254-consumer-validator
    app.kubernetes.io/name: ed254-consumer-validator
    app.kubernetes.io/part-of: ed254-consumer-validator
type: Opaque
stringData:
  AMQP_BROKER_USERNAME: "admin"
  AMQP_BROKER_PASSWORD: "admin"
