apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swim-demo

resources:
  - ed254-consumer-validator-config.yaml
  - ed254-consumer-validator-amqp-credentials.yaml
  - deployment.yaml
  - ed254-consumer-validator-service.yaml
  - ed254-consumer-validator-route.yaml
  - ed254-consumer-validator-route-http.yaml
  # Certificates (already exist in cluster, uncomment to recreate):
  # - ed254-consumer-validator-server-cert.yaml
  # - ed254-consumer-validator-client-certificate.yaml

commonLabels:
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize

images:
  - name: quay.io/masales/swim-ed254-consumer-validator
    newTag: latest
